<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>io.github.de-gupta</groupId>
        <artifactId>cleanCrudParent</artifactId>
        <version>0.1.5</version>
    </parent>

    <artifactId>cleanCrud-generator</artifactId>
    <version>0.6.1-SNAPSHOT</version>
    <packaging>pom</packaging>
    <modules>
        <module>code-generation-model-implementation</module>
        <module>code-generation-template-implementation</module>
        <module>code-generation-orchestration</module>
        <module>code-generation-writing-implementation</module>
        <module>cleanCrud-generator-api</module>
        <module>cleanCrud-generator-master</module>
    </modules>

    <name>cleanCrud-generator</name>
    <description>A library for implementing clean architecture based crud operations</description>
    <url>https://github.com/de-gupta/cleanCrud-generator.git</url>

    <properties>
        <clean.crud.version>0.8.4</clean.crud.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>io.github.de-gupta</groupId>
            <artifactId>aletheia</artifactId>
        </dependency>
        <dependency>
            <groupId>io.github.de-gupta</groupId>
            <artifactId>athena</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <scm>
        <connection>scm:git:git@github.com:de-gupta/cleanCrud-generator.git</connection>
        <developerConnection>scm:git:git@github.com:de-gupta/cleanCrud-generator.git</developerConnection>
        <url>https://github.com/de-gupta/cleanCrud-generator.git</url>
        <tag>HEAD</tag>
    </scm>
</project>