package de.gupta.clean.crud.generator.code.generation.template.api.domain.model.selection;

public enum TemplateGroup
{
	COMMON,
	CONFIGURATION,
	DOMAIN_MODELS,
	DOMAIN_SUPPORT,
	API_DTOS,
	API_ADAPTERS,
	API_CONTROLLERS,
	PERSISTENCE_MODELS,
	PERSISTENCE_ADAPTERS,
	PERSISTENCE_REPOSITORIES,
	PERSISTENCE_HISTORY,
	SECURITY,
	USE_CASE_FETCH,
	USE_CASE_SAVE,
	USE_CASE_UPDATE,
	USE_CASE_DELETE
}
