inputs.baseModelSourceCodeFilePath=${CLEANCRUD_BASE_MODEL_FILE}
inputs.persistenceModelSourceCodeFilePath=${CLEANCRUD_PERSISTENCE_MODEL_FILE}
genericTypes.domain.U=String
genericTypes.domain.V=Integer
genericTypes.persistence.U=String
genericTypes.persistence.V=Integer
genericTypes.api.U=String
genericTypes.api.V=Integer
generation.groups=COMMON,CONFIGURATION,DOMAIN_MODELS,DOMAIN_SUPPORT,API_DTOS,API_ADAPTERS,API_CONTROLLERS,PERSISTENCE_MODELS,PERSISTENCE_ADAPTERS,PERSISTENCE_REPOSITORIES,PERSISTENCE_HISTORY,SECURITY,USE_CASE_FETCH,USE_CASE_SAVE,USE_CASE_UPDATE,USE_CASE_DELETE
overwrite.defaultOverwrite=true
historized=true
